PieShop/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PieShop.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

PieShop/Controllers/PieController.cs
using Microsoft.AspNetCore.Mvc;
using PieShop.Models;
using PieShop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PieShop.Controllers
{
    public class PieController : Controller
    {
        private readonly IPieRepository _pieRepository;
        private readonly ICategoryRepository _categoryRepository;

        public PieController(ICategoryRepository categoryRepository, IPieRepository pieRepository)
        {
            _pieRepository = pieRepository;
            _categoryRepository = categoryRepository;
        }

        //public ViewResult List()
        //{
        //    _PieListViewModel pieListViewModel = new _PieListViewModel();
        //    pieListViewModel.Pies = _pieRepository.AllPies;

        //    pieListViewModel.currentCategory = "Cheese Cake";
        //    return View(pieListViewModel);
        //}

        public IActionResult Details(int id)
        {
            var pie = _pieRepository.GetPieById(id);
            if (id == null)
                return NotFound();
            return View(pie);
        }

        public IActionResult List(string category)
        {
            IEnumerable<Pie> pies;
            string currentCategory;

            if (string.IsNullOrEmpty(category))
            {
                pies = _pieRepository.AllPies.OrderBy(p => p.PieId);
                currentCategory = "All Pies";
            }
            else 
            {
                pies = _pieRepository.AllPies.Where(p => p.Category.CategoryName == category)
                    .OrderBy(p => p.PieId);

                currentCategory = _categoryRepository.AllCategories.FirstOrDefault(c => c.CategoryName == category).ToString();
            }

            return View(new _PieListViewModel {
                Pies = pies,
                currentCategory = currentCategory
            }) ;
        }
    }
}

PieShop/Views/Shared/_Carousel.cshtml
<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel" style="max-height:500px;overflow:hidden;">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/Images/pie1.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/Images/pie2.jpg" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="~/Images/pie.jpg" class="d-block w-100" alt="...">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

PieShop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.title</title>
    @*<link rel="stylesheet" href="~/css/c.css"  />*@
    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
</head>

<body>
    
    
        <nav class="navbar navbar-expand-lg navbar-light bg-primary">
            <div class="container">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-action="index" asp-controller="Home">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="List" asp-controller="Pie">Pies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Index" asp-controller="Contact">Contact</a>
                        </li>
                        @await Component.InvokeAsync("CategoryMenu")
                        @await Component.InvokeAsync("ShoppingCartSummary")
                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            @RenderBody()
        </div>

    @RenderSection("Scripts",required:false)
</body>

</html>
<script src="~/lib/twitter-bootstrap/js/bootstrap.js"></script>

PieShop/Views/Shared/_PieCard.cshtml
@model Pie


<div class="card" style="max-width: 500px; display:inline-block; margin:10px;">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="@Model.ImgUrl" class="img-fluid rounded-start" alt="@Model.Name">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">@Model.Name</h5>
                <h4 class="card-title">@Model.Price.ToString("c")</h4>
                <p class="card-text"> @Model.ShortDes</p>
                <a class="btn btn-outline-primary" asp-action="Details" asp-controller="Pie" asp-route-id="@Model.PieId">Details</a>
                <a class="btn btn-outline-primary" asp-action="AddToShoppingCart" asp-controller="ShoppingCart" asp-route-pieid="@Model.PieId">Add to Cart<i class="fas fa-cart-plus"></i></a>
            </div>
        </div>
    </div>
</div>